aidanwhiteley/books

README.md, pom.xml, src/main/java/com/aidanwhiteley/books/controller/BookController.java, src/main/java/com/aidanwhiteley/books/controller/LogonController.java, src/main/java/com/aidanwhiteley/books/controller/config/HttpCookieOAuth2AuthorizationRequestRepository.java, src/main/java/com/aidanwhiteley/books/controller/config/WebSecurityConfiguration.java, src/main/java/com/aidanwhiteley/books/controller/jwt/JwtAuthenticationFilter.java, src/main/java/com/aidanwhiteley/books/controller/jwt/JwtAuthenticationService.java, src/main/java/com/aidanwhiteley/books/repository/dtos/BooksByRating.java, src/main/java/com/aidanwhiteley/books/service/UserService.java, src/main/java/com/aidanwhiteley/books/util/Oauth2AuthenticationUtils.java, src/main/resources/application.yml, src/main/resources/logback-spring.xml, src/test/java/com/aidanwhiteley/books/controller/BookControllerTestUtils.java, src/test/java/com/aidanwhiteley/books/controller/BookSecureControllerTest.java, src/test/java/com/aidanwhiteley/books/controller/UserControllerTest.java, src/test/java/com/aidanwhiteley/books/service/UserServiceTest.java, src/test/java/com/aidanwhiteley/books/util/IntegrationTest.java
Merging in the work to make the application use Spring Security 5 for OAuth2 based logons - while configuring this code to use cookies rather than HTTP session state.
=> Spring security 5 stateless

pom.xml, src/main/java/com/aidanwhiteley/books/controller/UserController.java, src/main/java/com/aidanwhiteley/books/controller/config/HttpCookieOAuth2AuthorizationRequestRepository.java, src/main/java/com/aidanwhiteley/books/controller/config/WebSecurityConfiguration.java, src/main/java/com/aidanwhiteley/books/controller/jwt/JwtAuthentication.java, src/main/java/com/aidanwhiteley/books/controller/jwt/JwtAuthenticationService.java, src/main/resources/application-dev.yml, src/main/resources/application-integration.yml, src/main/resources/application-test.yml, src/main/resources/application.yml
Integrate sonar fixups into main branch
=> Sonar fixes

pom.xml
testing out an uplift to Spring Boot to new version 2.0.6
=> Uplift to Spring Boot 2.0.6

TO_DO.txt
Testing pull requests and protected branches
Fixes # n/a
=> Testing pull requests template

TO_DO.txt
=> Conflicting branches2

src/main/java/com/aidanwhiteley/books/controller/BookSecureController.java, src/main/java/com/aidanwhiteley/books/domain/Book.java, src/main/java/com/aidanwhiteley/books/domain/Comment.java, src/test/java/com/aidanwhiteley/books/controller/FeedsControllerTest.java
=> Code style fixups

pom.xml
=> Setting up 0.2.2 for development

pom.xml, src/main/java/com/aidanwhiteley/books/controller/config/HttpCookieOAuth2AuthorizationRequestRepository.java, src/main/java/com/aidanwhiteley/books/controller/jwt/JwtAuthenticationService.java, src/main/java/com/aidanwhiteley/books/repository/GoogleBooksDaoSync.java, src/main/java/com/aidanwhiteley/books/repository/UserRepositoryImpl.java
=> Spring boot 2.1.1

pom.xml
=> Preparing for 0.3.0 release on Spring Boot 2.1.0

src/main/java/com/aidanwhiteley/books/controller/LogonController.java, src/main/java/com/aidanwhiteley/books/controller/UserController.java, src/main/java/com/aidanwhiteley/books/controller/config/WebSecurityConfiguration.java, src/main/java/com/aidanwhiteley/books/controller/jwt/JwtAuthenticationService.java, src/main/java/com/aidanwhiteley/books/controller/jwt/JwtUtils.java, src/main/java/com/aidanwhiteley/books/domain/User.java, src/main/java/com/aidanwhiteley/books/service/UserService.java, src/main/resources/application-dev.yml, src/main/resources/application-test.yml, src/main/resources/application.yml, src/test/java/com/aidanwhiteley/books/controller/UserControllerTest.java, src/test/java/com/aidanwhiteley/books/repository/BookRepositoryTest.java, src/test/java/com/aidanwhiteley/books/repository/GoogleBooksDaoSyncTest.java, src/test/java/com/aidanwhiteley/books/util/ActuatorTest.java, src/test/resources/logback.xml
Trying to bring in spring-boot-admin-2 changes to develop
=> Spring boot admin 2

.travis.yml, README.md, src/main/java/com/aidanwhiteley/books/controller/UserController.java, src/main/java/com/aidanwhiteley/books/controller/config/WebSecurityConfiguration.java, src/main/java/com/aidanwhiteley/books/controller/jwt/JwtAuthenticationService.java, src/main/java/com/aidanwhiteley/books/domain/User.java, src/test/java/com/aidanwhiteley/books/controller/BookSecureControllerWithMocksTest.java, src/test/java/com/aidanwhiteley/books/repository/BookRepositoryTest.java, src/test/java/com/aidanwhiteley/books/repository/GoogleBookDaoAsyncTest.java, src/test/java/com/aidanwhiteley/books/repository/GoogleBooksDaoSyncTest.java, src/test/java/com/aidanwhiteley/books/repository/UserRepositoryTest.java, src/test/java/com/aidanwhiteley/books/service/SignUpNotificationServiceTest.java, src/test/java/com/aidanwhiteley/books/service/SummaryStatsTest.java, src/test/java/com/aidanwhiteley/books/service/UserServiceTest.java, src/test/java/com/aidanwhiteley/books/util/ActuatorTest.java, src/test/java/com/aidanwhiteley/books/util/SiteRssFeedTest.java, src/test/resources/logback.xml
=> Codacy fixups

README.md
=> LGTM badges

README.md, src/main/java/com/aidanwhiteley/books/util/preprod/DataLoader.java
LGTM Fixes 2
Fixes resource closure leaks an a readme change
=> 2nd set LGTM fixes - resource closures

src/main/java/com/aidanwhiteley/books/controller/UserController.java, src/main/java/com/aidanwhiteley/books/controller/jwt/JwtAuthenticationService.java, src/main/java/com/aidanwhiteley/books/util/preprod/DataLoader.java, src/main/resources/application.yml, src/test/java/com/aidanwhiteley/books/controller/BookControllerTestUtils.java, src/test/java/com/aidanwhiteley/books/controller/UserControllerTest.java, src/test/java/com/aidanwhiteley/books/controller/jwt/JwtAuthenticationServiceTest.java, src/test/java/com/aidanwhiteley/books/controller/jwt/JwtUtilsTest.java, src/test/resources/logback.xml
=> Test coverage fixups

src/main/java/com/aidanwhiteley/books/controller/BookSecureController.java, src/main/java/com/aidanwhiteley/books/util/preprod/DataLoader.java, src/test/java/com/aidanwhiteley/books/controller/BookSecureControllerTest.java, src/test/java/com/aidanwhiteley/books/repository/GoogleBooksDaoSyncTest.java, src/test/resources/mappings/c.a.b.r.GoogleBooksDaoSyncTest.confirmFindbyBookServiceUnavailable.json
=> Minor code coverage updates

src/main/java/com/aidanwhiteley/books/controller/config/HttpCookieOAuth2AuthorizationRequestRepository.java, src/main/java/com/aidanwhiteley/books/controller/jwt/JwtAuthenticationService.java, src/test/java/com/aidanwhiteley/books/domain/OwnerTest.java
=> Minor coverage additions

lgtm.yml, src/test/java/com/aidanwhiteley/books/controller/RestApiExceptionHandlerTest.java
=> More code coverage

README.md, docker-compose.yaml, pom.xml, src/main/java/com/aidanwhiteley/books/controller/jwt/JwtAuthenticationService.java, src/main/java/com/aidanwhiteley/books/util/preprod/MongoJavaServerConfig.java, src/main/java/com/aidanwhiteley/books/util/preprod/PreProdWarnings.java, src/main/resources/application-container-demo-no-auth.yml, src/main/resources/application-dev-mongo-java-server.yml, src/main/resources/application.yml, src/main/resources/logback-spring.xml, src/test/resources/logback.xml
=> Mongo server no auth 1

.env
=> Updated example .env

src/main/java/com/aidanwhiteley/books/controller/config/WebSecurityConfiguration.java
=> lgtm csrf ignore

pom.xml
=> Dependabot/maven/org.springframework.boot spring boot starter parent 2.3.1.release

pom.xml
=> Update to Boot 2.4.2 and Cloud 2020.0.1

pom.xml, src/main/java/com/aidanwhiteley/books/util/preprod/DataLoader.java, src/main/resources/application-ci.yml, src/main/resources/application-cloudy.yml, src/main/resources/application-container-demo-no-auth.yml, src/main/resources/application-dev-mongo-java-server-no-auth.yml, src/main/resources/application-dev-mongo-java-server.yml, src/main/resources/application-dev-mongodb-no-auth.yml, src/main/resources/application-dev-mongodb.yml, src/test/resources/logback.xml
=> Jan 24 deps upgrades
